### PR TITLE
Support Intel dGPU/iGPU platforms.

### PR DESCRIPTION
**Pull request by feng-intel**
Thanks for your review.

### CODE REVIEW

**Comment by ankan-ban** [comment]
Nice job @feng-intel! 
I didn't know sycl is so similar to CUDA. 
I see that you have copied the cuda implementation into a new folder and modified it. Given that the implementation doesn't share any code, is there any advantage of having it part of this repo (vs having it in a separate repo)?

**Comment by feng-intel** [comment]
The advantage is user can compare the cuda code with sycl code I think. Thanks.

**Comment by feng-intel** [comment]
Hi Ankan, any update?

**Comment by ankan-ban** [comment]
If you think it's useful to have in same repo, I don't have any concerns. Agree that some people may find it useful. Merging.

**Pull request merged**
