### PR TITLE
Cache swapping

### PR DESCRIPTION
**Pull request by GilesBathgate**
@ankan-ban I am wondering if you can help me. I have attempted to reduce the memory footprint so I can run the 13b model on my NVIDIA GeForce RTX 3080, with only 10GB of VRAM. The idea is to swap kv_cache to host memory for the last n layers, obviously, this will incur a performance hit, but not too much, based on my testing.

The code in the PR works for 7b (I think), but I am having trouble getting the 13b model to work.

**UPDATE: It now works! But could still do with some review to make it better, please.**

### CODE REVIEW

**Comment by GilesBathgate** [comment]
13b example output:

```
./llama2_q4 model-13b.bin -n 512 -i "There once was a"

Model params:- 
dim: 5120 
hidden_dim: 13824
n_heads: 40
n_kv_heads: 40
n_layers: 40
seq_len: 4096
vocab_size: 32000
rope_theta: 10000

Loading Weights... done!

Encoding Prompt... Done!
There once was a young man named Tim. Tim was a bit of a restless spirit, always looking for the next adventure. Tim had grown up in a small town in the Midwest, but restlessness had prompted him to move to California to pursue a career in the film industry. Tim had always been fascineless with the Golden State’elesslesslesslesslesslesslesslesslesslesslesslesslesslesslesslesslesslesslesslesslesslesslesslesslesslesslesslesslesslesslesslesslesslesslesslesslesslesslesslesslesslesslesslesslesslesslesslesslesslesslesslesslesslesslesslesslesslesslesslesslesslesslesslesslesslesslesslesslesslesslesslesslesslesslesslesslesslesslesslesslesslesslesslesslesslesslesslesslesslesslesslesslesslesslesslesslesslesslesslesslesslesslesslesslesslesslesslesslesslesslesslesslesslesslesslesslesslesslesslesslesslesslesslesslesslesslesslesslesslesslesslesslesslesslesslesslesslesslesslesslesslesslesslesslesslesslesslesslesslesslesslesslesslesslesslesslesslesslesslesslesslesslesslesslesslesslesslesslesslesslesslesslesslesslesslesslesslesslesslesslesslesslesslesslesslesslesslesslesslesslesslesslesslesslesslesslesslesslesslesslesslesslesslesslesslesslesslesslesslesslesslesslesslesslesslesslesslesslesslesslesslesslesslesslesslesslesslesslesslesslesslesslesslesslesslesslesslesslesslesslesslesslesslesslesslesslesslesslesslesslesslesslesslesslesslesslesslesslesslesslesslesslesslesslesslesslesslesslesslesslesslesslesslesslesslesslesslesslesslesslesslesslesslesslesslesslesslesslesslesslesslesslesslesslesslesslesslesslesslesslesslesslesslesslesslesslesslesslesslesslesslesslesslesslesslesslesslesslesslesslesslesslesslesslesslesslesslesslesslesslesslesslesslesslesslesslesslesslesslesslesslesslesslesslesslesslesslesslesslesslesslesslesslesslesslesslesslesslesslesslesslesslesslesslesslesslesslesslesslesslesslesslesslesslesslesslesslesslesslesslesslesslesslesslesslesslesslesslesslesslesslesslesslesslesslesslesslesslesslesslesslesslesslesslesslesslesslesslesslesslesslesslesslesslesslesslesslesslesslesslesslesslesslesslesslesslesslesslesslesslesslesslesslesslesslessless

achieved tok/s: 81.720774. Tokens: 511, seconds: 6.253
```

**Comment by ankan-ban** [comment]
>run the 13b model on my NVIDIA GeForce RTX 3080, with only 10GB of VRAM
Which model are you trying? 13b model with INT4 should be ~7GB + couple of GBs at max for KV cache - should already fit in 10GB 3080 ?
I think keeping some weights in system memory would be easier (and maybe it will be faster to run those layers on CPU instead - my understanding is llama.cpp does this).

**Comment by GilesBathgate** [comment]
@ankan-ban Its the 13B model and it does takes 7416MiB. I put some getchar() to pause the execution during allocate, and use nvidia-smi . Then it has to allocate K cache which takes it up to 9016MiB, and then it fails to allocate V cache which would take an additional 1600 MiB , so it total I need 10616 MiB, but the card only has 10240 MiB

**Comment by ankan-ban** [comment]
Ok. I see. Right now the code allocates the worst-case size for key and value caches (which I believe is assuming max seq len of 4096 which is the max supported by llama models). If you just want to quickly try running this model, I think easiest solution would be to add another command line param that allows the user to override the max_seq_len to a smaller value (I think other inference libraries already has such an option).

**Comment by GilesBathgate** [comment]
@ankan-ban I didn't have much success implementing a configurable max_seq_len. Can we just use unified memory and not have to worry about the manual offloading?

**Comment by GilesBathgate** [comment]
There is a similar (better) idea here, layer based inference: https://www.youtube.com/watch?v=WOTCViHmsOw

**Pull request closed without merging**
